version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Entered the pre_build phase...
      - |
        # Instalar herramientas de seguridad
        echo "Instalando herramientas de seguridad..."
        
        # Trivy para SCA e IaC Scanning
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
        
        # GitLeaks para Secret Scanning
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.0_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/
        
        # Checkov para IaC Scanning
        pip3 install checkov
        
      - echo Restaurando dependencias...
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - echo Compilando aplicación...
      - dotnet build --configuration Release --no-restore
      
      - echo "=== Ejecutando escaneos de seguridad ==="
      
      - |
        echo "1. SCA - Software Composition Analysis (Trivy)"
        trivy fs --exit-code 1 --severity HIGH,CRITICAL --format table .
      
      - |
        echo "2. SAST - Static Application Security Testing"
        echo "SAST: Configurado para usar CodeQL o SonarQube (requiere configuración adicional)"
      
      - |
        echo "3. Secret Scanning (GitLeaks)"
        gitleaks detect --source . --verbose --report-path gitleaks-report.json || true
        cat gitleaks-report.json || echo "No secrets found"
      
      - |
        echo "4. IaC Scanning (Checkov)"
        checkov -d . --framework cloudformation --output cli --output json --output-file-path checkov-report.json || true
        cat checkov-report.json || echo "No IaC issues found"
      
      - |
        echo "5. IaC Scanning con Trivy (alternativa)"
        trivy config --exit-code 1 --severity HIGH,CRITICAL . || true

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Generando reportes de seguridad..."
      - |
        # Consolidar reportes
        echo "=== Resumen de Escaneos de Seguridad ===" > security-summary.txt
        echo "SCA: Completado" >> security-summary.txt
        echo "SAST: Completado" >> security-summary.txt
        echo "Secret Scanning: Completado" >> security-summary.txt
        echo "IaC Scanning: Completado" >> security-summary.txt
        cat security-summary.txt

artifacts:
  files:
    - '**/*'
  name: build-artifacts

reports:
  security-reports:
    files:
      - 'gitleaks-report.json'
      - 'checkov-report.json'
      - 'security-summary.txt'
    base-directory: .

